name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: macOS-13
    strategy:
      matrix:
        xcode:
          - '14.3.1'
          - '15.0'
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - run: bazelisk test //...
